### ISSUE TITLE
Minus Numbers

### ISSUE THREAD

**Issue by Saad-Alhuss** [alkoumi/laravel-arabic-tafqeet#1]
Hello,

There is an issue with the minus numbers, when we add any minus number it is showing as صفر, but if the value is 1000.1 

it will show a positive integer, and it will be better if the money can support negative numbers.

Thanks for this great tool.

**Comment by alkoumi** [comment]
Thanks for these good words brother

Recommendations!!!  Please try `alkoumi/laravel-arabic-numbers` instead.

**Comment by MohsenAlyafei** [comment]
السلام عليكم ورحمة الله وبركاته.

هناك بعض الأخطاء الإملائية في الكتابة. يمكنك مقارنة الناتج من الكود بهذا الكود الذي نشرته هنا:

وهو كود عام لتفقيط العملات بجافاسكربكت أخذا بعين الإعتبار الإملاء الصحيح. أتمنى أن ينال على إعجابكم. وهناك شرح مبسط للدالة.


https://stackoverflow.com/questions/24594535/convert-arabic-numbers-to-words-with-javascript/71356825#71356825

**Comment by alkoumi** [comment]
thanks
