### ISSUE TITLE
Undefine Function Error

### ISSUE THREAD

**Issue by rrahulpatne** [alkoumi/laravel-arabic-tafqeet#7]
Hello,

I hope you are doing well,

We have tried to use your code in our application but we are getting the following error, Can you help us to solve the following error,

atal error: Uncaught Error: Call to undefined function AliAbdalla\Tafqeet\Core\money_format() in C:\xampp\htdocs\tafqeet-master\src\core\Tafqeet.php:95 Stack trace: #0 C:\xampp\htdocs\tafqeet-master\test.php(7): AliAbdalla\Tafqeet\Core\Tafqeet::arablic(30, 'usd') #1 {main} thrown in C:\xampp\htdocs\tafqeet-master\src\core\Tafqeet.php on line 95Fatal error: Uncaught Error: Call to undefined function AliAbdalla\Tafqeet\Core\money_format() in C:\xampp\htdocs\tafqeet-master\src\core\Tafqeet.php:95 Stack trace: #0 C:\xampp\htdocs\tafqeet-master\test.php(7): AliAbdalla\Tafqeet\Core\Tafqeet::arablic(30, 'usd') #1 {main} thrown in C:\xampp\htdocs\tafqeet-master\src\core\Tafqeet.php on line 95

**Comment by alkoumi** [comment]
Hello there, fine 

this package for the Laravel framework only ... I think you did not use it for the Laravel, I can see that from you errors

**Comment by rrahulpatne** [comment]
We are using laraval 7.2 only.

**Comment by alkoumi** [comment]
Hi , look to this code here 
`AliAbdalla\Tafqeet\Core\Tafqeet::arablic(30, 'usd')`

if you follow the documentation 
it must be same as 

`Alkoumi\LaravelArabicTafqeet\Tafqeet::inArabic(30,'usd');`

the result must be 
`"فقط ثلاثون دولاراً لاغير"`
<img width="900" alt="Screen Shot 1441-07-17 at 11 46 57 AM" src="https://user-images.githubusercontent.com/10585943/76503620-34dc3300-6457-11ea-8af6-091a8c17c48f.png">
